# -*- coding: utf-8 -*-
"""Machine Learning Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1Ls2kqELJtGxvcn1eZ0VE-59EpDh6K-
"""

import numpy as np

A = np.array([[1.1, 1.2, 1.3],
              [2.4, 2.5, 2.6],
              [3.7, 3.8, 3.9]])

B = np.array([[4.1, 4.2, 4.3],
              [5.4, 5.5, 5.6],
              [6.7, 6.8, 6.9]])

A @ B

AB = np.zeros((A.shape[0], B.shape[1]))

for i, row in enumerate(A):
    for j, column in enumerate(B.T):
        AB[i, j] = row.dot(column)

AB

AB = np.zeros((A.shape[0], B.shape[1]))

for i, row in enumerate(A):
    AB[i] = row.dot(B)

AB

AB = np.zeros((A.shape[0], B.shape[1]))

for j, column in enumerate(B.T):
    AB[:, j] = A.dot(column[:, None]).flatten()

AB

AB = np.zeros((A.shape[1], B.shape[0]))

for column_A, row_B in zip(A.T, B):
    AB += column_A[:, None].dot(row_B[None, :])

AB

AB = np.zeros((A.shape[0], B.shape[1]))

for column_A, row_B in zip(A.T, B):
    AB += np.outer(column_A, row_B)

AB

"""# Answer"""

A = np.array([[1.1, 1.2, 1.3, 1.4],
              [2.1, 2.2, 2.3, 2.4],
              [3.1, 3.2, 3.3, 3.4],
              [4.1, 4.2, 4.3, 4.4]])

B = np.array([[5.1, 5.2, 5.3, 5.4],
              [6.1, 6.2, 6.3, 6.4],
              [7.1, 7.2, 7.3, 7.4],
              [8.1, 8.2, 8.3, 8.4]])

A @ B

A1, A2 = A[:2, :2], A[:2, 2:]
A3, A4 = A[2:, :2], A[2:, 2:]

B1, B2 = B[:2, :2], B[:2, 2:]
B3, B4 = B[2:, :2], B[2:, 2:]

C1, C2 = A1@B1 + A2@B3, A1@B2 + A2@B4
C3, C4 = A3@B1 + A4@B3, A3@B2 + A4@B4

AB = np.vstack((np.hstack((C1, C2)),
                np.hstack((C3, C4))))

AB